version: '3.8'

services:
  frontend-test:
    build:
      context: ./to-do-app-frontend
      dockerfile: Dockerfile.test
    container_name: todo-frontend-test
    ports:
      - "5123:5123"
    environment:
      - NODE_ENV=test
    command: ["npm", "run", "test", "--", "--run"]

  backend-test:
    build:
      context: ./to-do-app-backend
      dockerfile: Dockerfile.test
    container_name: todo-backend-test
    environment:
      - SPRING_PROFILES_ACTIVE=test
    command: ["./gradlew", "test", "--no-daemon"] 