version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5005:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  pgdata:

networks:
  todo-network:
    driver: bridge
